import React from 'react';
import ScoreboardLogo from '../icons/scoreboard.svg';

const About = () => {
  return (
        <div className = "main text">
            <img src={ScoreboardLogo}  alt="logo"/>
            <h2>What even is this?</h2>
            <p>My family really loves to play games, but there are some games that are fairly tedious to keep score during. (If I had a nickel ever
            time we used a sharpie on a paper plate, I'd be rich) This site is an attempt to digitalize a scoresheet for some of our favorite games:</p>
            <ul>
                <li>Bank</li>
                <li>Rook</li>
                <li>And Nertz</li>
                <li>(I also plan on including a generic score sheet later)</li>
            </ul>
            <p> The general idea is that someone will act as the host, and will start the game and input the scores as they go. Everyone else can 
            access the game with a code generated by the host, and they can log into a view only spectator page so they can see the current scores. Everyone
            will also have access to the scoreboard page, which mimics a traditional pen and paper score sheet.</p>
            <p>Currently, only Bank is designed, so that is the only active link, although the other one's should be fairly similar. Bank is a straightforward
            dice game where everyone takes turns rolling dice, and you add the result to the total score. Anyone can "bank" that score in between rolls, because
            if someone rolls a seven, all of the points are lost. But you don't want to bank too early, because if someone rolls doubles, the points in the 
            middle double too.</p>
        </div>
    );
};

export default About;